### ISSUE TITLE
How about Sigamal, C-Sigamal and Sims (simplification sigamal) on python

### ISSUE THREAD

**Issue by Dastgsm** [Krijn-math/Constant-time-CSURF-CRADS#1]
Did you plan to make a code about Sigamal, C-Sigamal and Sims (simplification sigamal) on python; There is any code on magma about Sigamal but I don't have this software and can't experiment : http://tomoriya.work/code.html.

Chears,

**Comment by Krijn-math** [comment]
We do not have plans to implement Sigamal, C-Sigamal or Sims in this project: the main focus is to compare the performance of radical isogenies versus 'traditional' isogenies in terms of finite field operations.
